// Adapter layer for the Phosphor icon set.
//
// Every file in this directory keeps its original filename and its original
// intrinsic size, so the 90 files that import them change by zero lines.
// Phosphor defaults to size="1em"; the legacy set was 16x16 for most icons
// but 24x24 for 24 of them, and 40 call sites pass only `h-4` and rely on the
// intrinsic width to keep the glyph square. So each wrapper restates its size
// from this table rather than inheriting Phosphor's default.
//
// The full table is generated by scripts/convert-icons.mjs, which captures
// each legacy icon's original width/height before overwriting it — so the
// table and the wrappers can never drift.
//
// Imported (not `export … from`) because intrinsicProps below needs a local
// binding to read, not just a re-export for importers of this module.
import { INTRINSIC_SIZE } from './_sizes.generated'
export { INTRINSIC_SIZE }

export function intrinsicProps(name) {
  const size = INTRINSIC_SIZE[name]
  if (!size) {
    throw new Error(
      `No intrinsic size recorded for icon "${name}". Add it to INTRINSIC_SIZE ` +
        `in components/Icons/_phosphor.js — guessing a size silently shifts ` +
        `every call site that passes only a height class.`,
    )
  }
  const [width, height] = size
  return { width, height }
}
