// Adapter layer for the Phosphor icon set.
//
// Every file in this directory keeps its original filename and its original
// intrinsic size, so the 90 files that import them change by zero lines.
// Phosphor defaults to size="1em"; the legacy set was 16x16 for most icons
// but 24x24 for 24 of them, and 40 call sites pass only `h-4` and rely on the
// intrinsic width to keep the glyph square. So each wrapper restates its size
// from this table rather than inheriting Phosphor's default.
//
// Hand-written here: only the two entries this file's own tests need. The
// full ~106-entry table is generated by scripts/convert-icons.mjs in the
// task that converts the remaining icons.
export const INTRINSIC_SIZE = {
  BellIcon: [16, 16],
  DocumentIcon: [24, 24],
}

export function intrinsicProps(name) {
  const size = INTRINSIC_SIZE[name]
  if (!size) {
    throw new Error(
      `No intrinsic size recorded for icon "${name}". Add it to INTRINSIC_SIZE ` +
        `in components/Icons/_phosphor.js — guessing a size silently shifts ` +
        `every call site that passes only a height class.`,
    )
  }
  const [width, height] = size
  return { width, height }
}
